/**
 * Idempotency helper for mobile-app endpoints.
 *
 * Mobile clients send an offline-sync queue: when a request returns 2xx but the
 * response is lost (flaky LTE, app killed mid-response), the queue retries the
 * same payload — with the same uuid `clientRequestId`. Without dedupe, that
 * would mutate state twice (e.g. two check-ins on one visit). With dedupe, the
 * retry hits this log and returns the original response body verbatim.
 *
 * Usage in a route:
 *
 *   const cached = await getCachedResponse(tenantId, clientRequestId);
 *   if (cached) return reply.code(cached.responseStatus).send(cached.responseBody);
 *   // …do the mutation, build `result`…
 *   await recordResponse({ tenantId, clientRequestId, userId, route, status: 200, body: result });
 *   return reply.send(result);
 *
 * The `clientRequestId` itself is generated by the mobile client (uuid v4) and
 * stored in the local sync-queue row so retries reuse it.
 */

import type { Prisma } from "@prisma/client";
import { prisma } from "./prisma.js";

export interface CachedClientResponse {
  responseStatus: number;
  responseBody: Prisma.JsonValue;
}

/** Look up a previously logged response, or null if this is a fresh request. */
export async function getCachedResponse(
  tenantId: string,
  clientRequestId: string
): Promise<CachedClientResponse | null> {
  const row = await prisma.clientRequestLog.findUnique({
    where: { tenantId_clientRequestId: { tenantId, clientRequestId } },
    select: { responseStatus: true, responseBody: true }
  });
  return row;
}

/** Persist a 2xx response so future retries return the same body. */
export async function recordResponse(opts: {
  tenantId: string;
  clientRequestId: string;
  userId: string;
  route: string;
  status: number;
  body: Prisma.InputJsonValue;
}): Promise<void> {
  // Race: two retries arriving in parallel could both see no cache and both
  // proceed. The composite PK then makes the second insert fail. We swallow
  // the unique-violation because the first writer already succeeded and the
  // second handler's mutation will fail downstream anyway (e.g. PLANNED →
  // CHECKED_IN transition only matches one row).
  await prisma.clientRequestLog
    .create({
      data: {
        tenantId: opts.tenantId,
        clientRequestId: opts.clientRequestId,
        userId: opts.userId,
        route: opts.route,
        responseStatus: opts.status,
        responseBody: opts.body
      }
    })
    .catch(() => {});
}
