import { PrismaClient, VisitStatus, VisitType } from "@prisma/client";
import { ids, daysFromNow } from "./shared.js";

export async function seedVisits(prisma: PrismaClient) {
  await prisma.visit.createMany({
    data: [
      { id: ids.visit01, tenantId: ids.tenant, repId: ids.rep,  customerId: ids.custAcme,     dealId: ids.deal01, visitNo: "V-000001", visitType: VisitType.PLANNED,   status: VisitStatus.CHECKED_OUT, plannedAt: daysFromNow(-12), checkInAt: daysFromNow(-12), checkOutAt: daysFromNow(-12), checkInLat: 13.7563, checkInLng: 100.5679, objective: "สำรวจพื้นที่และวัดขนาดชั้น 12–15 เพื่อวางผัง Workstation", result: "วัดพื้นที่ได้ 1,800 ตร.ม. ชั้นละ 450 ตร.ม. ลูกค้าต้องการ Open Plan 150 ที่นั่ง ขอเพิ่มห้องประชุมย่อย 4 ห้อง และโซนพักผ่อน 1 โซน" },
      { id: ids.visit02, tenantId: ids.tenant, repId: ids.rep,  customerId: ids.custSiamTech, dealId: ids.deal02, visitNo: "V-000002", visitType: VisitType.PLANNED,   status: VisitStatus.CHECKED_OUT, plannedAt: daysFromNow(-19), checkInAt: daysFromNow(-19), checkOutAt: daysFromNow(-19), checkInLat: 13.7274, checkInLng: 100.5175, objective: "ประชุมกับทีมอาคารเพื่อกำหนดสเปคโต๊ะประชุม Board Room", result: "ห้อง Board Room ขนาด 12x8m ต้องการโต๊ะ 3m ลายไม้ European Oak นั่งได้ 12 คน พร้อมตู้ข้างผนัง ส่งใบเสนอราคาได้ทันที" },
      { id: ids.visit03, tenantId: ids.tenant, repId: ids.rep2, customerId: ids.custBKKFood,  dealId: ids.deal08, visitNo: "V-000003", visitType: VisitType.PLANNED,   status: VisitStatus.CHECKED_OUT, plannedAt: daysFromNow(-20), checkInAt: daysFromNow(-20), checkOutAt: daysFromNow(-20), checkInLat: 13.7200, checkInLng: 100.5250, objective: "สำรวจสำนักงานใหญ่ 3 ชั้นเพื่อวางแผนรีโนเวท", result: "ตรวจสอบแล้ว ชั้น 4–6 รวม 3,200 ตร.ม. โครงสร้างเดิมดีพอ ต้องเปลี่ยนเฟอร์นิเจอร์ทั้งหมด ลูกค้าต้องการระยะเวลาดำเนินการไม่เกิน 90 วัน" },
      { id: ids.visit04, tenantId: ids.tenant, repId: ids.rep2, customerId: ids.custThaiSteel,dealId: ids.deal09, visitNo: "V-000004", visitType: VisitType.PLANNED,   status: VisitStatus.CHECKED_OUT, plannedAt: daysFromNow(-15), checkInAt: daysFromNow(-15), checkOutAt: daysFromNow(-15), checkInLat: 12.7018, checkInLng: 101.1401, objective: "สำรวจและวัดพื้นที่ติดตั้งผนังกั้นห้อง Modular ชั้น 4–6", result: "วัดแนวผนังรวม 280 เมตร ชั้น 4 ต้องการระบบกระจกบานเลื่อน ชั้น 5–6 ผนังทึบ กำหนดส่งแบบ Shop Drawing ภายใน 2 สัปดาห์" },
      { id: ids.visit05, tenantId: ids.tenant, repId: ids.rep3, customerId: ids.custCentral,  dealId: ids.deal14, visitNo: "V-000005", visitType: VisitType.PLANNED,   status: VisitStatus.CHECKED_OUT, plannedAt: daysFromNow(-25), checkInAt: daysFromNow(-25), checkOutAt: daysFromNow(-25), checkInLat: 13.7466, checkInLng: 100.5393, objective: "นำเสนอ Concept Design ต่อคณะกรรมการโครงการ Tower B", result: "นำเสนอ 3 Concept ต่อกรรมการ 9 คน CFO ชอบ Concept B (Modular ขยายได้) ประหยัดพื้นที่ 18% อนุมัติให้จัดทำ Detailed Design ต่อ" },
      { id: ids.visit06, tenantId: ids.tenant, repId: ids.rep3, customerId: ids.custOmega,    dealId: ids.deal19, visitNo: "V-000006", visitType: VisitType.PLANNED,   status: VisitStatus.CHECKED_OUT, plannedAt: daysFromNow(-35), checkInAt: daysFromNow(-35), checkOutAt: daysFromNow(-35), checkInLat: 13.7200, checkInLng: 100.5300, objective: "ประชุม Kickoff และสำรวจอาคาร 8 ชั้นเพื่อวางแผน Mega Project", result: "ทำ Workshop เต็มวัน กำหนด Theme 3 แบบ ลูกค้าชอบแนวทาง Biophilic + Minimal เริ่ม Mock-up 1 ห้องที่ชั้น 3 ก่อนอนุมัติทั้งโครงการ" },
      { id: ids.visit07, tenantId: ids.tenant, repId: ids.rep,  customerId: ids.custAcme,     dealId: ids.deal03, visitNo: "V-000007", visitType: VisitType.UNPLANNED, status: VisitStatus.CHECKED_IN,  plannedAt: daysFromNow(0),  checkInAt: daysFromNow(0),  checkInLat: 13.7563, checkInLng: 100.5679, checkInSelfie: "r2://tenant_demo/selfies/checkin-demo.jpg", objective: "ติดตามการต่อรองราคาและนำเสนอตัวอย่าง Sample Board สีใหม่" },
      { id: ids.visit08, tenantId: ids.tenant, repId: ids.rep2, customerId: ids.custBKKFood,  dealId: ids.deal08, visitNo: "V-000008", visitType: VisitType.PLANNED,   status: VisitStatus.PLANNED,     plannedAt: daysFromNow(1),  objective: "นำเสนอข้อเสนอแบบแบ่งเฟสและเงื่อนไขการชำระเงินขั้นสุดท้าย" },
      // Somchai extra visits
      { id: ids.visit09, tenantId: ids.tenant, repId: ids.rep,  customerId: ids.custViva,     dealId: ids.deal06, visitNo: "V-000009", visitType: VisitType.PLANNED,   status: VisitStatus.CHECKED_OUT, plannedAt: daysFromNow(-9),  checkInAt: daysFromNow(-9),  checkOutAt: daysFromNow(-9),  checkInLat: 13.7700, checkInLng: 100.5600, objective: "นำเสนอตัวอย่างชุดรับแขก Lobby และสีผ้าตกแต่ง", result: "ลูกค้าชอบผ้า Velvet สีน้ำเงินเข้ม กำลังรออนุมัติงบประมาณจากคณะกรรมการบริษัท คาดว่าได้คำตอบภายใน 2 สัปดาห์" },
      { id: ids.visit10, tenantId: ids.tenant, repId: ids.rep,  customerId: ids.custNorth,    dealId: ids.deal07, visitNo: "V-000010", visitType: VisitType.PLANNED,   status: VisitStatus.CHECKED_OUT, plannedAt: daysFromNow(-16), checkInAt: daysFromNow(-16), checkOutAt: daysFromNow(-16), checkInLat: 18.8004, checkInLng: 98.9600,  objective: "ประชุมเพื่อวัดขนาดห้องและกำหนด Layout โต๊ะทำงานและตู้เก็บเอกสาร", result: "พื้นที่สำนักงาน 320 ตร.ม. ต้องการโต๊ะ Kadeem 18 ตัว เก้าอี้ Mesh 18 ตัว และตู้เอกสาร 2 บาน 10 ใบ ลูกค้าชอบ Layout แบบ L-shape" },
      { id: ids.visit11, tenantId: ids.tenant, repId: ids.rep,  customerId: ids.custSiamTech, dealId: ids.deal25, visitNo: "V-000011", visitType: VisitType.PLANNED,   status: VisitStatus.CHECKED_OUT, plannedAt: daysFromNow(-10), checkInAt: daysFromNow(-10), checkOutAt: daysFromNow(-10), checkInLat: 13.7274, checkInLng: 100.5175, objective: "สำรวจสภาพเก้าอี้และโต๊ะเดิมชั้น 10 เพื่อประเมินของที่จะเปลี่ยน", result: "ตรวจสอบแล้ว โต๊ะ 45 ตัวและเก้าอี้ 80 ตัวต้องเปลี่ยนทั้งหมด เฟอร์นิเจอร์เก่าอายุกว่า 8 ปีสภาพไม่ดี ส่งใบเสนอราคาเบื้องต้นแล้ว" },
      { id: ids.visit12, tenantId: ids.tenant, repId: ids.rep,  customerId: ids.custGolden,               visitNo: "V-000012", visitType: VisitType.UNPLANNED, status: VisitStatus.CHECKED_OUT, plannedAt: daysFromNow(-6),  checkInAt: daysFromNow(-6),  checkOutAt: daysFromNow(-6),  checkInLat: 13.7520, checkInLng: 100.5580, objective: "แวะเยี่ยมเยียนและอัพเดทโครงการที่กำลังจะเปิดตัวใหม่", result: "คุยกับคุณบุญรอด พบว่ามีโครงการ Phase 2 กำลังจะเริ่ม ต้องการเฟอร์นิเจอร์สำนักงานไซต์งานชั่วคราว 20 ชุด จะส่ง Quotation ภายในสัปดาห์นี้" },
      { id: ids.visit13, tenantId: ids.tenant, repId: ids.rep,  customerId: ids.custAcme,     dealId: ids.deal23, visitNo: "V-000013", visitType: VisitType.PLANNED,   status: VisitStatus.CHECKED_OUT, plannedAt: daysFromNow(-3),  checkInAt: daysFromNow(-3),  checkOutAt: daysFromNow(-3),  checkInLat: 13.7563, checkInLng: 100.5679, objective: "วัดพื้นที่แผนกใหม่และนำเสนอ Layout โต๊ะทำงาน Acker", result: "แผนกใหม่ชั้น 11 ขนาด 250 ตร.ม. ต้องการ Workstation 20 ชุดในแบบ Cluster 4 คน ลูกค้าขอเพิ่มฉากกั้นความสูง 120 ซม. ส่งแบบ Revised ใหม่ภายใน 3 วัน" },
      { id: ids.visit14, tenantId: ids.tenant, repId: ids.rep,  customerId: ids.custAcme,     dealId: ids.deal01, visitNo: "V-000014", visitType: VisitType.PLANNED,   status: VisitStatus.PLANNED,     plannedAt: daysFromNow(2),  objective: "นำเสนอ Revised Layout ชั้น 12–15 หลังรับ Feedback จาก Design Team ลูกค้า" },
      { id: ids.visit15, tenantId: ids.tenant, repId: ids.rep,  customerId: ids.custSiamTech, dealId: ids.deal02, visitNo: "V-000015", visitType: VisitType.PLANNED,   status: VisitStatus.PLANNED,     plannedAt: daysFromNow(5),  objective: "นำเสนอตัวอย่าง Mock-up โต๊ะประชุม European Oak พร้อม Quotation ฉบับสมบูรณ์" },
      { id: ids.visit16, tenantId: ids.tenant, repId: ids.rep,  customerId: ids.custViva,     dealId: ids.deal06, visitNo: "V-000016", visitType: VisitType.PLANNED,   status: VisitStatus.PLANNED,     plannedAt: daysFromNow(8),  objective: "ติดตามผลอนุมัติงบประมาณจากคณะกรรมการและปิดดีลชุดรับแขก Lobby" },
      // Somchai additional 10 visits
      { id: ids.visit17, tenantId: ids.tenant, repId: ids.rep,  customerId: ids.custMega,     dealId: ids.deal10, visitNo: "V-000017", visitType: VisitType.PLANNED,   status: VisitStatus.CHECKED_OUT, plannedAt: daysFromNow(-25), checkInAt: daysFromNow(-25), checkOutAt: daysFromNow(-25), checkInLat: 13.8100, checkInLng: 100.5450, objective: "นำเสนอโซลูชัน Workstation แบบ Modular สำหรับแผนกวิศวกรรม 40 คน", result: "ลูกค้าสนใจรุ่น Acker Flex สูงสุด ขอตัวอย่างวัสดุและเปรียบเทียบสี Warm Grey vs Charcoal จะตอบกลับภายใน 1 สัปดาห์" },
      { id: ids.visit18, tenantId: ids.tenant, repId: ids.rep,  customerId: ids.custThaiSteel,dealId: ids.deal11, visitNo: "V-000018", visitType: VisitType.PLANNED,   status: VisitStatus.CHECKED_OUT, plannedAt: daysFromNow(-22), checkInAt: daysFromNow(-22), checkOutAt: daysFromNow(-22), checkInLat: 13.6100, checkInLng: 100.8200, objective: "ประเมินความต้องการเฟอร์นิเจอร์โรงงานและห้องควบคุมผลิต", result: "ต้องการโต๊ะทำงานทนทานรุ่น Heavy-Duty 30 ตัว เก้าอี้ Anti-Static 30 ตัว และ Locker 60 ล็อก ลูกค้าขอ Delivery แบบแยก 2 งวด" },
      { id: ids.visit19, tenantId: ids.tenant, repId: ids.rep,  customerId: ids.custEastAsia,             visitNo: "V-000019", visitType: VisitType.UNPLANNED, status: VisitStatus.CHECKED_OUT, plannedAt: daysFromNow(-18), checkInAt: daysFromNow(-18), checkOutAt: daysFromNow(-18), checkInLat: 13.7350, checkInLng: 100.5950, objective: "แวะเยี่ยมเยียนหลังส่งมอบงานเฟส 1 เพื่อรับ Feedback", result: "ลูกค้าพอใจงานติดตั้งมาก ขอให้เสนอราคาเฟส 2 ห้องประชุมชั้น 7–9 รวม 6 ห้อง คาดงบประมาณ 1.2M–1.5M บาท" },
      { id: ids.visit20, tenantId: ids.tenant, repId: ids.rep,  customerId: ids.custPremier,  dealId: ids.deal12, visitNo: "V-000020", visitType: VisitType.PLANNED,   status: VisitStatus.CHECKED_OUT, plannedAt: daysFromNow(-14), checkInAt: daysFromNow(-14), checkOutAt: daysFromNow(-14), checkInLat: 13.7160, checkInLng: 100.5330, objective: "นำเสนอ Quotation ฉบับแก้ไขหลังปรับ Spec เก้าอี้ Executive และโต๊ะ Conference", result: "ลูกค้าอนุมัติ Spec ใหม่แล้ว รอลายเซ็น PO จากกรรมการผู้จัดการ คาดได้ภายใน 3 วันทำการ" },
      { id: ids.visit21, tenantId: ids.tenant, repId: ids.rep,  customerId: ids.custRajaPlas, dealId: ids.deal13, visitNo: "V-000021", visitType: VisitType.PLANNED,   status: VisitStatus.CHECKED_OUT, plannedAt: daysFromNow(-11), checkInAt: daysFromNow(-11), checkOutAt: daysFromNow(-11), checkInLat: 14.0100, checkInLng: 100.6200, objective: "สำรวจพื้นที่คลังสินค้าและออฟฟิศในนิคมอุตสาหกรรมเพื่อวางแผนจัดวาง", result: "ออฟฟิศ 180 ตร.ม. ต้องการ Workstation 15 ชุด ห้องประชุม 1 ห้อง และ Break Area ลูกค้าต้องการ Delivery ก่อนเปิดไลน์ผลิตวันที่ 1 มิถุนายน" },
      { id: ids.visit22, tenantId: ids.tenant, repId: ids.rep,  customerId: ids.custCentral,  dealId: ids.deal14, visitNo: "V-000022", visitType: VisitType.PLANNED,   status: VisitStatus.CHECKED_OUT, plannedAt: daysFromNow(-7),  checkInAt: daysFromNow(-7),  checkOutAt: daysFromNow(-7),  checkInLat: 13.7480, checkInLng: 100.5350, objective: "ติดตาม PO และหารือเรื่องตารางติดตั้งเฟอร์นิเจอร์สำนักงานกลาง", result: "ได้รับ PO เรียบร้อย มูลค่า 2.3M บาท นัดติดตั้งวันที่ 20–25 พ.ค. ประสานงานกับทีม Logistics แล้ว" },
      { id: ids.visit23, tenantId: ids.tenant, repId: ids.rep,  customerId: ids.custOmega,                visitNo: "V-000023", visitType: VisitType.UNPLANNED, status: VisitStatus.CHECKED_OUT, plannedAt: daysFromNow(-4),  checkInAt: daysFromNow(-4),  checkOutAt: daysFromNow(-4),  checkInLat: 13.7600, checkInLng: 100.6000, objective: "ติดตามการแก้ไขเก้าอี้ที่มีปัญหาหลังติดตั้ง", result: "ตรวจสอบ 5 ตัวที่ลูกค้าแจ้ง พบกลไกปรับความสูงชำรุด 2 ตัว ประสานทีมช่างเข้าเปลี่ยนภายใน 3 วัน ลูกค้าพอใจการดูแลหลังการขาย" },
      { id: ids.visit24, tenantId: ids.tenant, repId: ids.rep,  customerId: ids.custAmarin,   dealId: ids.deal15, visitNo: "V-000024", visitType: VisitType.PLANNED,   status: VisitStatus.PLANNED,     plannedAt: daysFromNow(3),  objective: "นำเสนอ Concept Design ห้องสมุดและพื้นที่อ่านหนังสือโรงแรมบูติก" },
      { id: ids.visit25, tenantId: ids.tenant, repId: ids.rep,  customerId: ids.custBKKFood,  dealId: ids.deal16, visitNo: "V-000025", visitType: VisitType.PLANNED,   status: VisitStatus.PLANNED,     plannedAt: daysFromNow(6),  objective: "หารือ Spec โต๊ะ Canteen และเก้าอี้กันน้ำ 120 ชุดสำหรับโรงอาหารพนักงาน" },
      { id: ids.visit26, tenantId: ids.tenant, repId: ids.rep,  customerId: ids.custMega,     dealId: ids.deal10, visitNo: "V-000026", visitType: VisitType.PLANNED,   status: VisitStatus.PLANNED,     plannedAt: daysFromNow(10), objective: "นำตัวอย่าง Workstation Modular ไปให้ทีมวิศวกรทดลองใช้ก่อนตัดสินใจ" }
    ]
  });
}
